# Stage 1: Build
FROM node:18-alpine AS builder

WORKDIR /app
COPY . .
RUN npm ci && npm run build


# Stage 2: Run
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80